---
title: "dispatchFunctionalTest"
author: "Theodore Van Rooy"
date: "December 8, 2014"
output: html_document
---

This document tests out all of the funcitonality and reports on what results from the function calls.  

Helps to test out which parts of the code might not be working.

### Base Data Generation

```{r}
library(DPSOpenCPU)
library(knitr)


demoData = baseData(pickups = 1000, numTrucks = 10, numStations = 3, numDropOffs = 10)


### base station optimization
baseStationOpt = optimizeBaseStations(baseData=demoData)



```

### Dispatching

```{r}

dispatch = dispatchQueue(demoData,windowsAhead = 12)



### make a plot of the dispatch locations



### summary tables
dispatchSummary = dispatchSummaries(dispatch = dispatch, baseData = demoData)

### summary metrics
dispatchMetrics = dispatchBriefSummary(dispatchSummary = dispatchSummary, baseData = demoData)



```


### Viable Alternatives

```{r}

vAltTable = viableAlternatives(baseData=demoData, dispatch=dispatch, loadName=dispatch$dispatch$WELL_NAME[11])


```
### Modifying the queue, pickups and dynamically rescheduling the dispatch

